// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsmgjidhovzzejdgufzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzbWdqaWRob3Z6emVqZGd1ZnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDA3OTgsImV4cCI6MjA2ODQ3Njc5OH0.ZsH39w59CEUUs9FBmKElNgMMkoG_-VHTjMz3kT22V-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});